# Generated by Django 5.2.7 on 2025-10-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes_count",
            field=models.IntegerField(default=0, verbose_name="추천수"),
        ),
    ]
